### ISSUE TITLE
Mismatch between PyPi and conda-forge versions

### ISSUE THREAD

**Issue by valeriupredoi** [conda-forge/xgboost-feedstock#105]
Hey guys, am sure you are aware of this, hence I may sound like Dr Obvious, but heads up xgboost is at 1.7 on c-f and 1.7.1 on pypi, this is tripping [Readthedocs](https://readthedocs.org/projects/esmvaltool/builds/18558513/) builds for us - many thanks for your good work! :beer:

**Comment by hcho3** [comment]
Can you fix your build so that the mismatch doesn't break it? Typically there is some delay between PyPI and Conda releases.

**Comment by jakirkham** [comment]
Would also add anyone is welcome to submit a PR to update the Conda package

**Comment by valeriupredoi** [comment]
@hcho3 we have now, but it wasn't too straightforward since I had to dig out some new feature in the Readthedocs build configuration that averts the default pip install in eager mode - the root cause of the issue - RTD's pip installation was updating packages even if there was no need to do that; if you guys run into this issue too, use jobs in the RTD's config eg https://github.com/ESMValGroup/ESMValTool/pull/2913/files - @jakirkham absolutely, mate, I was planning on doing a PR here if you guys didn't beat me to it :grin: At any rate, cheers for your good work here, and apols if I came across annoying :smiley:

**Comment by jakirkham** [comment]
Gotcha maybe it is worth [raising an issue with RTD about adding `--no-deps` or similar to `pip`]( https://github.com/readthedocs/readthedocs.org/issues ). This would allow bypassing the `pip` install of the dependencies (especially when this was already done with Conda). Just a thought 🙂

**Comment by valeriupredoi** [comment]
Absolutely! Afraid there is one https://github.com/readthedocs/readthedocs.org/issues/8890 - alas, closed - they invoke some constraints they can't work against to do that. At least now there is configuration magic, to avoid it 🪄

**Comment by jakirkham** [comment]
That seems somewhat different since that is discussing how `pip` solves as opposed to simply skipping dependencies. So would suggest a new issue.

Think it may help also if you share your use case. Namely installing with Conda and then `pip install`ing the source. They may be more open to discussion when realizing two different package managers are trying to do the same thing and clobbering each other.

**Comment by valeriupredoi** [comment]
@jakirkham I totally took you up on that idea, and opened this one https://github.com/readthedocs/readthedocs.org/issues/9727 - cheers for suggesting, and thanks for your comments and suggestions here, mate :beer:
