### ISSUE TITLE
@conda-forge-admin rerender

### ISSUE THREAD

**Issue by beckermr** [conda-forge/xgboost-feedstock#124]

**Comment by jakirkham** [comment]
Was there a particular issue this was trying to fix?

**Comment by beckermr** [comment]
Trying to understand bot errors.

**Comment by jakirkham** [comment]
Is there a reference to the errors?

Also worth noting we are using `git` in this repo due to submodules that are needed

https://github.com/conda-forge/xgboost-feedstock/blob/fb10524285161d7ebc8bd35be268e894fde7e54b/recipe/meta.yaml#L9-L13

**Comment by beckermr** [comment]
Yes see the pr to close the r 4.3 migration.

**Comment by jakirkham** [comment]
This?

https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4750#issuecomment-1668640168

**Comment by beckermr** [comment]
Yep

**Comment by jakirkham** [comment]
Thanks Matt! 🙏

GHA doesn't render on my phone. So will look later

**Comment by jakirkham** [comment]
Looks like the bot issued a new migrator PR ( https://github.com/conda-forge/xgboost-feedstock/pull/126 )

**Comment by beckermr** [comment]
Yup! yay!
