### ISSUE TITLE
@conda-forge-admin, please add user @hcho3

### ISSUE THREAD

**Issue by hcho3** [conda-forge/xgboost-feedstock#141]
Adding myself as a maintainer

cc @jakirkham

**Comment by jakirkham** [comment]
Thanks Philip! 🙏

**Comment by jakirkham** [comment]
More details from the bot in this comment: https://github.com/conda-forge/xgboost-feedstock/commit/d57753c5802e5dbe5f29ac28a928e4ee0ff45893#commitcomment-130463037
