### ISSUE TITLE
Revisit macOS patch to use latest `libcxx` (aka 0002)

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/xgboost-feedstock#175]
Currently we have this patch for R on macOS, which passes `-D_LIBCPP_DISABLE_AVAILABILITY`

https://github.com/conda-forge/xgboost-feedstock/blob/44f54392837b13980c3a0d68d7b03c78b041b3c6/recipe/patches/0002-Enable-latest-libcxx-on-MacOS.patch#L10-L20

Though we are also passing this same flag in the build via `--configure-args`

https://github.com/conda-forge/xgboost-feedstock/blob/44f54392837b13980c3a0d68d7b03c78b041b3c6/recipe/install-r-xgboost.sh#L8

Am curious if we actually need both or if this patch can be dropped

**Comment by jakirkham** [comment]
For more context both changes were added as part of PR: https://github.com/conda-forge/xgboost-feedstock/pull/132

* The patch was added in commit: https://github.com/conda-forge/xgboost-feedstock/pull/132/commits/7df7e4ce80165d60b40c2f2d0b9643045e244001
* Meanwhile the flag was added in commit: https://github.com/conda-forge/xgboost-feedstock/pull/132/commits/f333e39d80a8659f8e7edefcb0ce14fab0f97b24

**Comment by hcho3** [comment]
We can keep the patch and drop the `--configure-args` flag.
