### ISSUE TITLE
xgboost 2.1.1 is not supported on this platform

### ISSUE THREAD

**Issue by xhochy** [conda-forge/xgboost-feedstock#190]
I'm seeing this issue across many platforms locally and in CI of other feedstocks, e.g. for `cuda 11.8` builds:

```
+ pip check
xgboost 2.1.1 requires nvidia-nccl-cu12, which is not installed.
xgboost 2.1.1 is not supported on this platform
```

For osx-*, it's only ( e.g.`xgboost-2.1.1-cpu_pyhb8f9a19_1`):

```
+ pip check
xgboost 2.1.1 is not supported on this platform
```

**Comment by jakirkham** [comment]
@hcho3 could you please take a look?

**Comment by jakirkham** [comment]
So the CUDA 11.8 & 12 packages appear to be fixed

However the CPU-only package is still showing an issue

```
$ pip check 
xgboost 2.1.1 is not supported on this platform
```

Am not sure why that is

Note: Did try installing `nccl` in the CPU-only case, but the error persists. So this doesn't appear to be as simple as checking for NCCL

**Comment by xhochy** [comment]
I looked at the nannyml case and am a bit confused. The `nannyml` job has `py-xgboost=2.1.1-cpu_pyhf829fab_3` where as the CI job here for build no 3 and CPU actually lists that it builds `py-xgboost=2.1.1-cpu_pyhc68e8b7_3`. https://anaconda.org/conda-forge/py-xgboost/files lists even more packages.

Looking at the OSX logs, we can see that the wheel are not actually `noarch`: xgboost-2.1.1-py3-none-macosx_12_0_x86_64.whl So we probably are mixing platforms here and the wheel tags don't carry the right information.

**Comment by xhochy** [comment]
Should be fixed by https://github.com/conda-forge/xgboost-feedstock/pull/194
