### ISSUE TITLE
don't use git_url for pulling the source

### ISSUE THREAD

**Issue by beckermr** [conda-forge/xgboost-feedstock#22]
See the title.

**Comment by beckermr** [comment]
So fun fact @CJ-Wright. Installing this package requires git submodules which are not in the source tarballs. Thus I think we have to use a git_url with hash.

**Comment by beckermr** [comment]
Closing unless you know a way around this.

**Comment by CJ-Wright** [comment]
hmm ok, that is annoying

**Comment by moble** [comment]
@beckermr @CJ-Wright [This page](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos) says "Repositories are usually larger than tarballs, draining shared CI time and bandwidth".  Is there something wrong with adding 
```
  git_depth: 1
```
here?  (I'm trying this in a new recipe.)

**Comment by beckermr** [comment]
That is not so much of a concern anymore but do feel free to add it if you'd like!
