### ISSUE TITLE
Use _py-xgboost-mutex to differentiate libxgboost CPU vs GPU

### ISSUE THREAD

**Issue by ksangeek** [conda-forge/xgboost-feedstock#23]
I see that `libxgboost` conda package also provides the CLI for `xgboost`, but I don't see a method for a user to select a CPU or a GPU variant of this.
Should there be a meta-packages named `libxgboost-cpu` and `libxgboost-gpu` to help users selectively install the variant they desire?

And also maybe `libxgboost` should have a dependency on the selection package `_py-xgboost-mutex` so that the CPU and the GPU variants are not wrongly installed?

@jjhelmus Pulling you in here for comments, based on your comments in https://github.com/conda-forge/xgboost-feedstock/issues/14

**Comment by beckermr** [comment]
Ack. I thought we had this right.

**Comment by beckermr** [comment]
So conda does not ship the GPU variant. 

We do depend on the mutex package to make sure the env is consistent. https://github.com/conda-forge/xgboost-feedstock/blob/master/recipe/meta.yaml#L70

Do you have an example of how this is going wrong?

**Comment by beckermr** [comment]
OK. So we cannot do this because the R package also depends on libxgboost. I am confused as to how you got an env to this state. You should not install libxgboost directly but instead you need to install one of the frontend packages that have the mutex dependencies.

**Comment by ksangeek** [comment]
I see that a user _could_ install `libxgboost` directly and I don't see anything to restrict a user from doing that e.g. https://anaconda.org/conda-forge/libxgboost. I think you might be referring to that it is not _common_ for a user to just install `libxgboost` conda package? Or am I missing something here?
My concern was only for the case when someone would just install `libxgboost` directly (who is just wants the `xgboost` CLI).

**Comment by beckermr** [comment]
Installing libxgboost directly is not how the package is supposed to be used, but yes of course people can do what they please.

I wonder if we should be separating the CLI from the lib package? Then we could use the mutex as it is supposed to work.

**Comment by ksangeek** [comment]
Yes, separating the CLI from `libxgboost` conda package would take care of the concern I brought up. Based on the discussion here, it seems that it is not expected for anyone to just install `libxgboost` and so is not a major concern anyway!
Thank You @beckermr for spending time on this.

**Comment by beckermr** [comment]
Happy to chat! I am going to leave this issue open for now.

**Comment by jakirkham** [comment]
Would it make sense to have a single mutex for all of these packages as they will all be dependent on `libxgboost` for CPU or GPU support?

**Comment by beckermr** [comment]
When you say "single mutex," what do you mean?

**Comment by jakirkham** [comment]
Sorry a single package to select GPU or CPU builds. Right now I see `_py-xgboost-mutex` and `_r-xgboost-mutex`. Am wondering if we can just have `_libxgboost-mutex`, which aligns C++, Python, and R. Does that make more sense?

**Comment by beckermr** [comment]
Ah ok. Does having a CPU python version installed in the env mean the GPU one cannot be? I don't know the internals well enough to understand the constraints here.

**Comment by jakirkham** [comment]
My guess is all packages using `libxgboost` need to be either CPU or GPU. That said, I don't know if the CPU/GPU parts extend outside of `libxgboost` or if they are contained within a common public APIs at the C++ level. If it's the latter, the Python and R bindings may be no different whether they are built to target CPU or GPU as only `libxgboost` would be affected. @RAMitchell, could you please provide us some guidance here?

**Comment by RAMitchell** [comment]
None of the Python code is different, the binary compiled for GPU use can safely be used on a system without a GPU. It will only fail if a user tries to call some GPU function and the cuda runtime does not exist.

**Comment by beckermr** [comment]
so we can just compile in gpu support for everything? why did we have the mutex in the first place? I copied it out of the main anaconda channels.

**Comment by jakirkham** [comment]
Do you happen to remember the author of these changes? Maybe we can ask them?

**Comment by beckermr** [comment]
looks like it was @jjhelmus and/or @mingwandroid

**Comment by ksangeek** [comment]
There are a few things I'd like to add here -
1. From a conda packaging perspective, the GPU variant would need to depend on `cudatoolkit` for `build` and `run` as used here - https://github.com/AnacondaRecipes/xgboost-feedstock/blob/885f8b2583def2146d494254d04ce05456704d3b/recipe/meta.yaml#L47. But the CPU variant does not need that!
2, I have seen the objects built for libxgboost GPU variant (which includes objects for CUDA code) make the library very bulky. So, regardless of point 1. I think it is still a good idea to have separate conda packages for the GPU and CPU variant.
Ref - https://github.com/AnacondaRecipes/xgboost-feedstock/blob/885f8b2583def2146d494254d04ce05456704d3b/recipe/build.sh#L16-L19

While I had opened this issue, the idea was very close to what @jakirkham brought up here wrt to R. But my request was to include the dependency of `- {{ pin_subpackage('_py-xgboost-mutex', exact=True) }}` in the run/host section of `libxgboost` package, so that the CPU and GPU versions are exclusive. Installing the GPU variant (on a system where CPU variant is already installed) should prompt to clear off the conflicting packages (which includes libxgboost). In the current form, this recipe will not prompt to remove `libxgboost`.

https://github.com/conda-forge/xgboost-feedstock/blob/521defb3c10cf9f5d95e127a14a238e29606aa6c/recipe/meta.yaml#L36-L49

And as @jakirkham brought up I am supportive of the idea to have a single mutex `_xgboost-mutex`, which aligns C++, Python, and R.

**Comment by mingwandroid** [comment]
If the gpu xgboost works just as well without gpus as the non-gpu xgboost then there's no good enough reason for the cpu variant to exist. 

Let's discard all idea of mutexes then?

**Comment by jakirkham** [comment]
Personally would be fine with either keeping one mutex or dropping.

It sounds to me like @ksangeek's concerns are basically about total install size, which seems like a valid concern to me (note: this does come up in other contexts). Do we have a sense of what the size difference is now?

**Comment by jakirkham** [comment]
Have added PR ( https://github.com/conda-forge/xgboost-feedstock/pull/35 ) to try and simplify CPU/GPU selection based on the discussion here. Please take a look and share your thoughts. 🙂

**Comment by jakirkham** [comment]
We've since added GPU/CPU packages here. There may very well still be work needed, but please try it out and let us know

**Comment by hcho3** [comment]
@jakirkham Can we close this out now?

**Comment by jakirkham** [comment]
Yes this is done

If we want to make other changes, we should start a new issue discussing those
