### ISSUE TITLE
Using CMake to build

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/xgboost-feedstock#27]
Currently it appears we are just using [`make` to build]( https://github.com/conda-forge/xgboost-feedstock/blob/521defb3c10cf9f5d95e127a14a238e29606aa6c/recipe/build.sh#L33 ). However [the installations docs]( https://xgboost.readthedocs.io/en/latest/build.html ) are geared primarily for CMake. What are people's thoughts on switching the build to CMake?

**Comment by beckermr** [comment]
Works for me but there have been ongoing issues with CMake and the new compilers. IDK what the status of that is exactly.

**Comment by jakirkham** [comment]
Which issues are you thinking of?

**Comment by jakirkham** [comment]
Are you just thinking of [the behavior with sysroot-ed compilers]( https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html#an-aside-on-cmake-and-sysroots )?

**Comment by beckermr** [comment]
I think so, but there were various ones (or the same one) that ran by on the gitter. I didn't follow this closely so if those issues are all resolved, then let's go for it.

**Comment by jakirkham** [comment]
Ok, thanks for the info. FWIW I'm willing to work through these issues to get this using CMake and send a PR. My hope is it will make it easier to enable different features in the build. Just wanted to make sure this path seemed reasonable first. 🙂

**Comment by jakirkham** [comment]
Have submitted PR ( https://github.com/conda-forge/xgboost-feedstock/pull/28 ) to start working on this.
