### ISSUE TITLE
Update to 0.90

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/xgboost-feedstock#29]
Would be good to update this to [the newest release, 0.90]( https://github.com/dmlc/xgboost/releases/tag/v0.90 ).

**Comment by beckermr** [comment]
This build drops python 2.X. I guess we should do that, but do we want to maintain a 2.X compatible release in another branch?

**Comment by jakirkham** [comment]
That seems reasonable.

**Comment by jakirkham** [comment]
Done in PR ( https://github.com/conda-forge/xgboost-feedstock/pull/31 ).
