### ISSUE TITLE
Upstream search path logic for `libxgboost`

### ISSUE THREAD

**Issue by hcho3** [conda-forge/xgboost-feedstock#51]

**Comment by jakirkham** [comment]
Here's [the patch]( https://github.com/conda-forge/xgboost-feedstock/blob/696ca06a4f429484a2c970b3c67c1f807481e7a9/recipe/0001-conda-Unbundle-libxgboost.-dll-dylib-so.patch ) for context.

**Comment by jakirkham** [comment]
Also relevant upstream issue ( https://github.com/dmlc/xgboost/issues/5386 ).

**Comment by jakirkham** [comment]
This is mostly resolved. Currently still carrying [this patch]( https://github.com/conda-forge/xgboost-feedstock/blob/3a31a070805a6790eeef1f82b1490673a3299161/recipe/0001-conda-Unbundle-libxgboost.-dll-dylib-so.patch )

**Comment by jakirkham** [comment]
Am proposing upstreaming the remainder of this patch in PR: https://github.com/dmlc/xgboost/pull/10643
